Task1 models
Kaid000/RAFwebsite pull request #1
Opened 2023-08-14 15:56 UTC by Kaid000

2023-08-14 19:11 UTC, BlazeOfSoul requested changes

2023-08-14 19:11 UTC, BlazeOfSoul commented on server/RAFwebsite.Models/User.cs
> +        public bool is_admin { get; set; }
Add Enum class UserRoles with User and Admin

2023-08-14 19:11 UTC, BlazeOfSoul commented on .gitignore
> +## Ignore Visual Studio temporary files, build results, and
Comment for all PR
Create a BaseEntity class and inherit all classes from it

2023-08-14 19:11 UTC, BlazeOfSoul commented on server/RAFwebsite.Models/AboutFaculty.cs
> +
Delete pass

2023-08-14 19:16 UTC, yarmoliq commented
Don't use internal. Use CamelCase for properties. Read on how to work properly with images (don't use base64 or whatever it is)

2023-08-14 19:18 UTC, yarmoliq requested changes

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/News.cs
> +    internal class News
Why New[s]?

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/News.cs
> +        public int news_id { get; set; }
Simply `Id`. Id is already in the news

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/News.cs
> +        public string image { get; set; }
same

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/News.cs
> +        public Event f_event { get; set; }
you can use @ to escape keyword usage.
Also, don't use event as a class name. change

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/Organization.cs
> +            public string organization_name { get; set; }
Rename to `Name`

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/Organization.cs
> +            public string? logo { get; set; }
Use files from the server

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/Organization.cs
> +            public string leader { get; set; }
Who is leader?

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/Panorama.cs
> +    internal class Panorama
Remove if it's a single Slider (it's called slider, not panorama) on the main page. If it is a something that will be used widely across the website, rename to slider, adjust ot use server files for images

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/RAFwebsite.Models.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Use 8

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/RAFwebsite.Models.csproj
> +    <OutputType>Exe</OutputType>
Why exe?

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/User.cs
> +        public int user_id { get; set; }
Simply `Id`

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/User.cs
> +        public string user_name { get; set; }
rename to first name

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/User.cs
> +        public string user_surname { get; set; }
rename to last name

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/User.cs
> +        public string user_email { get; set; }
just email

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/User.cs
> +        public string user_phone { get; set; }
just `phone`

2023-08-14 19:18 UTC, yarmoliq commented on server/RAFwebsite.Models/User.cs
> +        public bool is_admin { get; set; }
Implement Roles, not just a flag

2023-08-16 14:24 UTC, Kaid000 commented on server/RAFwebsite.Models/User.cs
> +        public string image { get; set; }
Is it the class file for images ?

2023-08-16 14:30 UTC, Kaid000 commented on server/RAFwebsite.Models/News.cs
> +    internal class News
How to name this class correctly?

2023-08-16 14:43 UTC, Kaid000 commented on server/RAFwebsite.Models/RAFwebsite.Models.csproj
> +    <OutputType>Exe</OutputType>
What's would be?

2023-08-21 14:43 UTC, closed without merging